version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Dependencies
      - apt-get update && apt-get -y install xvfb libxss1 libappindicator1 libindicator7 fonts-liberation libasound2 libnspr4 libnss3 xdg-utils
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb && apt-get install -f
      - pip install selenium
  build:
    commands:
      - wget -N http://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - chmod +x chromedriver
      - mv -f chromedriver /usr/local/share/chromedriver
      - ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
      - ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
      - chmod u+x ./spec/selenium/chrome_test.py
      - python ./spec/selenium/chrome_test.py
  post_build:
    commands:
      - echo Build completed on `date`
