version: 0.2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_TestDeployOutput
      - ls
      - cat sha.txt
      - SOURCE_SHA=$(cat sha.txt)
      - DATE=$(date)
      - echo "${API_URL}/${SOURCE_SHA}"
      - curl -i -X POST -H "Authorization:token ${OAUTH_TOKEN}" "${API_URL}/${SOURCE_SHA}" -d "{\"state\":\"success\",\"description\":\"Deployed to production on ${DATE}\",\"context\":\"${CODEBUILD_INITIATOR}\",\"target_url\":\"https://${TARGET_URL}\"}"
